
version: '3'
services:
  wanglab-jupyter-template:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wanglab-jupyter-template
    volumes:
      - ./src:/home/jovyan/work/src:rw
      - ./data:/home/jovyan/work/data:rw
    ports:
    - "9000:8888"
    restart: unless-stopped
    command: jupyter notebook --ip='*' --port=8888 --no-browser --NotebookApp.token='YOUR_PASSWORD' --allow-root
    deploy:
     resources:
       limits:
         memory: 16000M