
version: '3'
services:
  wanglab-jupyter-template:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wanglab-jupyter-template
    volumes:
      - .:/home/jovyan/work:rw
    ports:
    - "9000:8888"
    restart: unless-stopped
    command: jupyter lab --ip='*' --port=8888 --no-browser --NotebookApp.token='YOUR_PASSWORD' --allow-root
    deploy:
     resources:
       limits:
         memory: 16000M
    environment:
      VIRTUAL_HOST: test.wanglab.science
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: test.wanglab.science
      LETSENCRYPT_EMAIL: miw023@ucsd.edu